2024-09-19 15:35:01,666 - ERROR - Error in load_sentle function for index 2: 'str' object has no attribute 'geometry'
2024-09-19 15:36:50,230 - INFO - Resolution: 10
2024-09-19 15:36:52,868 - INFO - > Available CUDA devices: 1
2024-09-19 15:36:52,869 - INFO - > Load the Minicube 0 ...
2024-09-19 15:36:52,955 - INFO - Resolution: 10
2024-09-19 15:36:54,322 - INFO - > Save the Minicube 0 ...
2024-09-19 15:49:34,855 - INFO - > Successfully saved the Minicube 0 at None/LUCAS_CPNS_Wheat_ES42_42062802_10.zarr ...
2024-09-19 15:49:34,857 - INFO - > Load the Minicube 1 ...
2024-09-19 15:49:34,884 - INFO - Resolution: 10
2024-09-19 15:49:36,272 - INFO - > Save the Minicube 1 ...
2024-09-19 15:53:43,081 - INFO - > Successfully saved the Minicube 1 at None/LUCAS_CPNS_Wheat_ES42_42082818_10.zarr ...
2024-09-19 15:53:43,083 - INFO - Total execution time: 1010.56 seconds
2024-09-19 15:57:28,351 - INFO - Resolution: 10
2024-09-19 15:57:29,838 - INFO - > Available CUDA devices: 1
2024-09-19 15:57:29,839 - INFO - > Load the Minicube 0 ...
2024-09-19 15:57:29,843 - INFO - Resolution: 10
2024-09-19 16:01:38,203 - INFO - Resolution: 10
2024-09-19 16:01:40,304 - INFO - > Available CUDA devices: 1
2024-09-19 16:01:40,305 - INFO - > Load the Minicube 0 ...
2024-09-19 16:01:40,329 - INFO - Resolution: 10
2024-09-19 16:01:41,960 - INFO - > Save the Minicube 0 ...
2024-09-19 16:28:16,729 - INFO - > Successfully saved the Minicube 0 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_42062802_10.zarr ...
2024-09-19 16:28:16,731 - INFO - > Load the Minicube 1 ...
2024-09-19 16:28:16,736 - INFO - Resolution: 10
2024-09-19 16:28:35,795 - INFO - > Save the Minicube 1 ...
2024-09-19 16:51:43,307 - INFO - > Successfully saved the Minicube 1 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_42082818_10.zarr ...
2024-09-19 16:51:43,309 - INFO - Total execution time: 3003.01 seconds
2024-09-19 17:02:12,881 - INFO - Resolution: 10
2024-09-19 17:02:15,026 - INFO - > Available CUDA devices: 1
2024-09-19 17:02:15,027 - ERROR - An error occurred in the main execution: 0
2024-09-19 17:02:15,031 - INFO - Total execution time: 0.01 seconds
2024-09-19 17:02:48,059 - INFO - Resolution: 10
2024-09-19 17:02:49,434 - INFO - > Available CUDA devices: 1
2024-09-19 17:02:49,434 - ERROR - An error occurred in the main execution: 0
2024-09-19 17:02:49,438 - INFO - Total execution time: 0.01 seconds
2024-09-19 17:03:11,333 - INFO - Resolution: 10
2024-09-19 17:03:12,523 - INFO - > Available CUDA devices: 1
2024-09-19 17:03:12,524 - ERROR - An error occurred in the main execution: 0
2024-09-19 17:03:12,528 - INFO - Total execution time: 0.01 seconds
2024-09-19 17:05:56,706 - INFO - Resolution: 10
2024-09-19 17:05:58,144 - INFO - > Available CUDA devices: 1
2024-09-19 17:05:58,145 - ERROR - An error occurred in the main execution: 0
2024-09-19 17:05:58,149 - INFO - Total execution time: 0.01 seconds
2024-09-19 17:06:23,195 - INFO - Resolution: 10
2024-09-19 17:06:24,436 - INFO - > Available CUDA devices: 1
2024-09-19 17:06:24,437 - ERROR - An error occurred in the main execution: 0
2024-09-19 17:06:24,441 - INFO - Total execution time: 0.01 seconds
2024-09-19 17:06:34,583 - INFO - Resolution: 10
2024-09-19 17:06:36,144 - INFO - > Available CUDA devices: 1
2024-09-19 17:06:36,145 - ERROR - An error occurred in the main execution: 0
2024-09-19 17:06:36,149 - INFO - Total execution time: 0.01 seconds
2024-09-19 17:09:03,354 - INFO - Resolution: 10
2024-09-19 17:09:04,728 - INFO - > Available CUDA devices: 1
2024-09-19 17:09:04,729 - ERROR - An error occurred in the main execution: 0
2024-09-19 17:09:04,736 - INFO - Total execution time: 0.01 seconds
2024-09-19 17:09:20,085 - INFO - Resolution: 10
2024-09-19 17:09:21,538 - INFO - > Available CUDA devices: 1
2024-09-19 17:09:21,539 - ERROR - An error occurred in the main execution: 'list' object has no attribute 'point_id'
2024-09-19 17:09:21,543 - INFO - Total execution time: 0.01 seconds
2024-09-19 17:16:10,420 - INFO - Resolution: 10
2024-09-19 17:16:15,562 - INFO - > Available CUDA devices: 1
2024-09-19 17:16:15,563 - ERROR - An error occurred in the main execution: 'list' object has no attribute 'point_id'
2024-09-19 17:16:15,568 - INFO - Total execution time: 0.01 seconds
2024-09-19 17:22:54,494 - INFO - Resolution: 10
2024-09-19 17:22:55,813 - INFO - > Available CUDA devices: 1
2024-09-19 17:22:55,814 - INFO - > Load the Minicube 0 ...
2024-09-19 17:22:55,834 - INFO - Resolution: 10
2024-09-19 17:22:57,409 - INFO - > Save the Minicube 0 ...
2024-09-19 17:23:24,646 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45555' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:23:24,650 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45546' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:23:24,655 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45551' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:23:24,659 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45550' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:23:24,667 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45549' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:23:24,693 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45552' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:23:24,745 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45547' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:23:24,765 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45548' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:23:24,772 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45553' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:24:12,474 - INFO - Resolution: 10
2024-09-19 17:24:13,898 - INFO - > Available CUDA devices: 1
2024-09-19 17:24:13,899 - INFO - > Load the Minicube 0 ...
2024-09-19 17:24:13,907 - INFO - Resolution: 10
2024-09-19 17:24:15,146 - INFO - > Save the Minicube 0 ...
2024-09-19 17:35:09,801 - INFO - > Successfully saved the Minicube 0 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32782004_10.zarr ...
2024-09-19 17:35:09,803 - INFO - > Load the Minicube 1 ...
2024-09-19 17:35:09,806 - INFO - Resolution: 10
2024-09-19 17:35:11,196 - INFO - > Save the Minicube 1 ...
2024-09-19 17:37:02,905 - INFO - > Successfully saved the Minicube 1 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32162000_10.zarr ...
2024-09-19 17:37:02,907 - INFO - > Load the Minicube 2 ...
2024-09-19 17:37:02,911 - INFO - Resolution: 10
2024-09-19 17:37:04,269 - INFO - > Save the Minicube 2 ...
2024-09-19 17:46:37,864 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61616' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:37,930 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61612' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:37,963 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61624' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:37,995 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61619' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,000 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61611' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,004 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61625' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,008 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61618' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,012 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61627' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,015 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61614' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,019 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61615' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,022 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61617' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,025 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61622' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,029 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61623' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,031 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61610' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,035 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61626' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,037 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61621' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,041 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61620' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-19 17:46:38,043 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61613' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:25,822 - INFO - Resolution: 10
2024-09-20 08:29:27,858 - INFO - > Available CUDA devices: 1
2024-09-20 08:29:27,858 - INFO - > Load the Minicube 0 ...
2024-09-20 08:29:27,863 - INFO - Resolution: 10
2024-09-20 08:29:29,367 - INFO - > Save the Minicube 0 ...
2024-09-20 08:29:29,393 - ERROR - An error occurred for index 0: path '' contains a group
2024-09-20 08:29:29,394 - INFO - > Load the Minicube 1 ...
2024-09-20 08:29:29,397 - INFO - Resolution: 10
2024-09-20 08:29:31,068 - INFO - > Save the Minicube 1 ...
2024-09-20 08:29:31,070 - ERROR - An error occurred for index 1: path '' contains a group
2024-09-20 08:29:31,073 - INFO - > Load the Minicube 2 ...
2024-09-20 08:29:31,077 - INFO - Resolution: 10
2024-09-20 08:29:32,351 - INFO - > Save the Minicube 2 ...
2024-09-20 08:29:32,353 - ERROR - An error occurred for index 2: path '' contains a group
2024-09-20 08:29:32,357 - INFO - > Load the Minicube 3 ...
2024-09-20 08:29:32,361 - INFO - Resolution: 10
2024-09-20 08:29:33,703 - INFO - > Save the Minicube 3 ...
2024-09-20 08:29:44,385 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-70' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,386 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-76' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,392 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-63' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,393 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-65' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,402 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-74' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,405 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-59' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,408 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-71' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,411 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-67' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,414 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-60' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,416 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-64' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,419 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-66' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,422 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-61' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,424 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-72' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,427 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-69' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,430 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-75' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,432 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-68' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,435 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-73' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:44,441 - ERROR - Task exception was never retrieved
future: <Task finished name='Task-62' coro=<Client._gather.<locals>.wait() done, defined at /net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py:2385> exception=AllExit()>
Traceback (most recent call last):
  File "/net/home/dschierbaum/.conda/envs/wp1v2/lib/python3.12/site-packages/distributed/client.py", line 2394, in wait
    raise AllExit()
distributed.client.AllExit
2024-09-20 08:29:59,567 - INFO - Resolution: 10
2024-09-20 08:30:01,724 - INFO - > Available CUDA devices: 1
2024-09-20 08:30:01,725 - INFO - > Load the Minicube 0 ...
2024-09-20 08:30:01,729 - INFO - Resolution: 10
2024-09-20 08:30:03,193 - INFO - > Save the Minicube 0 ...
2024-09-20 08:33:46,117 - INFO - > Successfully saved the Minicube 0 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32782004_10.zarr ...
2024-09-20 08:33:46,118 - INFO - > Load the Minicube 1 ...
2024-09-20 08:33:46,122 - INFO - Resolution: 10
2024-09-20 08:33:47,636 - INFO - > Save the Minicube 1 ...
2024-09-20 08:36:51,599 - INFO - > Successfully saved the Minicube 1 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32162000_10.zarr ...
2024-09-20 08:36:51,601 - INFO - > Load the Minicube 2 ...
2024-09-20 08:36:51,605 - INFO - Resolution: 10
2024-09-20 08:36:52,963 - INFO - > Save the Minicube 2 ...
2024-09-20 09:03:25,610 - INFO - > Successfully saved the Minicube 2 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32402112_10.zarr ...
2024-09-20 09:03:25,612 - INFO - > Load the Minicube 3 ...
2024-09-20 09:03:25,627 - INFO - Resolution: 10
2024-09-20 09:03:26,997 - INFO - > Save the Minicube 3 ...
2024-09-20 09:05:46,700 - INFO - > Successfully saved the Minicube 3 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32022048_10.zarr ...
2024-09-20 09:05:46,702 - INFO - > Load the Minicube 4 ...
2024-09-20 09:05:46,706 - INFO - Resolution: 10
2024-09-20 09:05:48,245 - INFO - > Save the Minicube 4 ...
2024-09-20 09:30:49,482 - INFO - > Successfully saved the Minicube 4 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_31381916_10.zarr ...
2024-09-20 09:30:49,484 - INFO - > Load the Minicube 5 ...
2024-09-20 09:30:49,489 - INFO - Resolution: 10
2024-09-20 09:30:51,824 - INFO - > Save the Minicube 5 ...
2024-09-20 09:32:51,163 - INFO - > Successfully saved the Minicube 5 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32181886_10.zarr ...
2024-09-20 09:32:51,165 - INFO - > Load the Minicube 6 ...
2024-09-20 09:32:51,170 - INFO - Resolution: 10
2024-09-20 09:32:52,655 - INFO - > Save the Minicube 6 ...
2024-09-20 09:57:20,805 - INFO - > Successfully saved the Minicube 6 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_30481980_10.zarr ...
2024-09-20 09:57:20,807 - INFO - > Load the Minicube 7 ...
2024-09-20 09:57:20,833 - INFO - Resolution: 10
2024-09-20 09:57:22,516 - INFO - > Save the Minicube 7 ...
2024-09-20 09:59:36,134 - INFO - > Successfully saved the Minicube 7 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32862062_10.zarr ...
2024-09-20 09:59:36,136 - INFO - > Load the Minicube 8 ...
2024-09-20 09:59:36,141 - INFO - Resolution: 10
2024-09-20 09:59:37,484 - INFO - > Save the Minicube 8 ...
2024-09-20 10:22:47,040 - INFO - > Successfully saved the Minicube 8 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32582084_10.zarr ...
2024-09-20 10:22:47,042 - INFO - > Load the Minicube 9 ...
2024-09-20 10:22:47,043 - INFO - Resolution: 10
2024-09-20 10:22:49,150 - INFO - > Save the Minicube 9 ...
2024-09-20 10:25:00,347 - INFO - > Successfully saved the Minicube 9 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_31761898_10.zarr ...
2024-09-20 10:25:00,349 - INFO - > Load the Minicube 10 ...
2024-09-20 10:25:00,355 - INFO - Resolution: 10
2024-09-20 10:25:01,869 - INFO - > Save the Minicube 10 ...
2024-09-20 11:10:02,810 - INFO - > Successfully saved the Minicube 10 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32502098_10.zarr ...
2024-09-20 11:10:02,812 - INFO - > Load the Minicube 11 ...
2024-09-20 11:10:02,828 - INFO - Resolution: 10
2024-09-20 11:10:04,564 - INFO - > Save the Minicube 11 ...
2024-09-20 11:11:15,227 - INFO - > Successfully saved the Minicube 11 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32981850_10.zarr ...
2024-09-20 11:11:15,229 - INFO - > Load the Minicube 12 ...
2024-09-20 11:11:15,233 - INFO - Resolution: 10
2024-09-20 11:11:16,617 - INFO - > Save the Minicube 12 ...
2024-09-20 12:00:51,047 - INFO - > Successfully saved the Minicube 12 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_33041856_10.zarr ...
2024-09-20 12:00:51,049 - INFO - > Load the Minicube 13 ...
2024-09-20 12:00:51,074 - INFO - Resolution: 10
2024-09-20 12:00:53,193 - INFO - > Save the Minicube 13 ...
2024-09-20 12:15:25,798 - INFO - > Successfully saved the Minicube 13 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_33062062_10.zarr ...
2024-09-20 12:15:25,799 - INFO - > Load the Minicube 14 ...
2024-09-20 12:15:25,871 - INFO - Resolution: 10
2024-09-20 12:15:28,040 - INFO - > Save the Minicube 14 ...
2024-09-20 12:17:52,365 - INFO - > Successfully saved the Minicube 14 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_33441856_10.zarr ...
2024-09-20 12:17:52,366 - INFO - > Load the Minicube 15 ...
2024-09-20 12:17:52,370 - INFO - Resolution: 10
2024-09-20 12:17:53,683 - INFO - > Save the Minicube 15 ...
2024-09-20 12:40:59,823 - ERROR - An error occurred for index 15: ('store-map-595028656c1e8ee43678e27987680fd2', 3, 0, 0, 0) cancelled for reason: scheduler-connection-lost.
Client lost the connection to the scheduler. Please check your connection and re-run your work.
2024-09-20 12:40:59,830 - INFO - > Load the Minicube 16 ...
2024-09-20 12:40:59,832 - INFO - Resolution: 10
2024-09-20 12:41:03,735 - INFO - > Save the Minicube 16 ...
2024-09-20 12:41:42,043 - INFO - > Successfully saved the Minicube 16 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_31962064_10.zarr ...
2024-09-20 12:41:42,046 - INFO - > Load the Minicube 17 ...
2024-09-20 12:41:42,050 - INFO - Resolution: 10
2024-09-20 12:41:43,388 - INFO - > Save the Minicube 17 ...
2024-09-20 12:42:23,415 - INFO - > Successfully saved the Minicube 17 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32362034_10.zarr ...
2024-09-20 12:42:23,417 - INFO - > Load the Minicube 18 ...
2024-09-20 12:42:23,424 - INFO - Resolution: 10
2024-09-20 12:42:25,263 - INFO - > Save the Minicube 18 ...
2024-09-20 12:43:25,848 - INFO - > Successfully saved the Minicube 18 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_33262044_10.zarr ...
2024-09-20 12:43:25,853 - INFO - > Load the Minicube 19 ...
2024-09-20 12:43:25,857 - INFO - Resolution: 10
2024-09-20 12:43:27,369 - INFO - > Save the Minicube 19 ...
2024-09-20 12:43:42,507 - INFO - > Successfully saved the Minicube 19 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32642090_10.zarr ...
2024-09-20 12:43:42,508 - INFO - > Load the Minicube 20 ...
2024-09-20 12:43:42,513 - INFO - Resolution: 10
2024-09-20 12:43:44,123 - INFO - > Save the Minicube 20 ...
2024-09-20 12:44:18,002 - INFO - > Successfully saved the Minicube 20 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_31361960_10.zarr ...
2024-09-20 12:44:18,004 - INFO - > Load the Minicube 21 ...
2024-09-20 12:44:18,008 - INFO - Resolution: 10
2024-09-20 12:44:19,342 - INFO - > Save the Minicube 21 ...
2024-09-20 12:44:33,819 - INFO - > Successfully saved the Minicube 21 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32742072_10.zarr ...
2024-09-20 12:44:33,820 - INFO - > Load the Minicube 22 ...
2024-09-20 12:44:33,827 - INFO - Resolution: 10
2024-09-20 12:44:35,460 - INFO - > Save the Minicube 22 ...
2024-09-20 12:45:09,951 - INFO - > Successfully saved the Minicube 22 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32182014_10.zarr ...
2024-09-20 12:45:09,954 - INFO - > Load the Minicube 23 ...
2024-09-20 12:45:09,957 - INFO - Resolution: 10
2024-09-20 12:45:11,635 - INFO - > Save the Minicube 23 ...
2024-09-20 12:45:26,028 - INFO - > Successfully saved the Minicube 23 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32202060_10.zarr ...
2024-09-20 12:45:26,029 - INFO - > Load the Minicube 24 ...
2024-09-20 12:45:26,033 - INFO - Resolution: 10
2024-09-20 12:45:27,500 - INFO - > Save the Minicube 24 ...
2024-09-20 12:45:46,762 - INFO - > Successfully saved the Minicube 24 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32322030_10.zarr ...
2024-09-20 12:45:46,764 - INFO - > Load the Minicube 25 ...
2024-09-20 12:45:46,787 - INFO - Resolution: 10
2024-09-20 12:45:48,134 - INFO - > Save the Minicube 25 ...
2024-09-20 12:46:05,855 - INFO - > Successfully saved the Minicube 25 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32522070_10.zarr ...
2024-09-20 12:46:05,858 - INFO - > Load the Minicube 26 ...
2024-09-20 12:46:05,861 - INFO - Resolution: 10
2024-09-20 12:46:07,232 - INFO - > Save the Minicube 26 ...
2024-09-20 12:46:26,965 - INFO - > Successfully saved the Minicube 26 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32541878_10.zarr ...
2024-09-20 12:46:26,968 - INFO - > Load the Minicube 27 ...
2024-09-20 12:46:26,971 - INFO - Resolution: 10
2024-09-20 12:46:28,300 - INFO - > Save the Minicube 27 ...
2024-09-20 12:46:50,761 - INFO - > Successfully saved the Minicube 27 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32902004_10.zarr ...
2024-09-20 12:46:50,763 - INFO - > Load the Minicube 28 ...
2024-09-20 12:46:50,768 - INFO - Resolution: 10
2024-09-20 12:46:52,370 - INFO - > Save the Minicube 28 ...
2024-09-20 12:47:31,274 - INFO - > Successfully saved the Minicube 28 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32581868_10.zarr ...
2024-09-20 12:47:31,276 - INFO - > Load the Minicube 29 ...
2024-09-20 12:47:31,280 - INFO - Resolution: 10
2024-09-20 12:47:32,908 - INFO - > Save the Minicube 29 ...
2024-09-20 12:48:15,358 - INFO - > Successfully saved the Minicube 29 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32621882_10.zarr ...
2024-09-20 12:48:15,360 - INFO - > Load the Minicube 30 ...
2024-09-20 12:48:15,364 - INFO - Resolution: 10
2024-09-20 12:48:17,148 - INFO - > Save the Minicube 30 ...
2024-09-20 12:48:30,489 - INFO - > Successfully saved the Minicube 30 at /net/projects/EO4BK/WP1/P1-EO4BK/data/Sent2/Wheat/Nut2/LUCAS_CPNS_Wheat_ES42_32442106_10.zarr ...
2024-09-20 12:48:30,491 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-20 12:48:30,494 - INFO - Total execution time: 15508.77 seconds
2024-09-25 08:49:14,167 - INFO - Resolution: 10
2024-09-25 08:49:14,999 - ERROR - Error in load_sentle function for index 2: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-25 10:21:50,572 - ERROR - Error in load_sentle function for index 2: single positional indexer is out-of-bounds
2024-09-25 10:26:41,905 - INFO - Resolution: 10
2024-09-25 10:26:42,775 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-25 10:27:48,898 - INFO - Resolution: 10
2024-09-25 10:27:49,748 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-25 10:29:09,505 - ERROR - Error in load_sentle function for index 1: single positional indexer is out-of-bounds
2024-09-25 10:29:17,356 - INFO - Resolution: 10
2024-09-25 10:29:18,158 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-25 10:37:14,130 - ERROR - Error in load_sentle function for index 2: single positional indexer is out-of-bounds
2024-09-25 10:37:27,848 - INFO - Resolution: 10
2024-09-25 10:37:28,634 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-25 11:23:38,147 - INFO - Resolution: 10
2024-09-25 11:34:34,083 - INFO - Resolution: 10
2024-09-25 11:34:35,727 - INFO - > Available CUDA devices: 1
2024-09-25 11:34:35,728 - INFO - > Load the Minicube 0 ...
2024-09-25 11:34:35,733 - INFO - Resolution: 10
2024-09-25 11:34:37,159 - INFO - > Save the Minicube 0 ...
2024-09-25 11:34:37,335 - ERROR - An error occurred for index 0: b'\x80\x05\x95`\x07\x00\x00\x00\x00\x00\x00\x8c\x16tblib.pickling_support\x94\x8c\x12unpickle_exception\x94\x93\x94(\x8c\x08builtins\x94\x8c\x0cRuntimeError\x94\x93\x94\x8c\xfaError during deserialization of the task graph. This frequently\noccurs if the Scheduler and Client have different environments.\nFor more information, see\nhttps://docs.dask.org/en/stable/deployment-considerations.html#consistent-software-environments\n\x94\x85\x94h\x02(h\x03\x8c\x13ModuleNotFoundError\x94\x93\x94\x8c\x19No module named \'cytoolz\'\x94\x85\x94Nh\x00\x8c\x12unpickle_traceback\x94\x93\x94\x8c\x05tblib\x94\x8c\x05Frame\x94\x93\x94)\x81\x94}\x94(\x8c\x08f_locals\x94}\x94\x8c\tf_globals\x94}\x94(\x8c\x08__name__\x94\x8c\x15distributed.scheduler\x94\x8c\x08__file__\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94u\x8c\x06f_code\x94h\x0e\x8c\x04Code\x94\x93\x94)\x81\x94}\x94(\x8c\x0bco_filename\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94\x8c\x07co_name\x94\x8c\x0cupdate_graph\x94\x8c\x0bco_argcount\x94K\x00\x8c\x11co_kwonlyargcount\x94K\x00\x8c\x0bco_varnames\x94)\x8c\nco_nlocals\x94K\x00\x8c\x0cco_stacksize\x94K\x00\x8c\x08co_flags\x94K@\x8c\x0eco_firstlineno\x94K\x00ub\x8c\x08f_lineno\x94M\x80\x12ubMJ\x12h\x0e\x8c\tTraceback\x94\x93\x94)\x81\x94}\x94(\x8c\x08tb_frame\x94h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1edistributed.protocol.serialize\x94h\x19\x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94h"\x8c\x0bdeserialize\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\xc1\x01ub\x8c\ttb_lineno\x94M\xc1\x01\x8c\x07tb_next\x94h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h5h\x19h6uh\x1bh\x1d)\x81\x94}\x94(h h9h"\x8c\x0cpickle_loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Koubh;Koh<h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1bdistributed.protocol.pickle\x94h\x19\x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94h"\x8c\x05loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Kcubh;K^ububub\x87\x94R\x94N\x89Nt\x94R\x94}\x94\x8c\x04name\x94\x8c\x07cytoolz\x94sbh\rh\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h\x18h\x19h\x1auh\x1bh\x1d)\x81\x94}\x94(h h!h"h#h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\x80\x12ubMS\x12N\x87\x94R\x94hU\x88Nt\x94R\x94.'
2024-09-25 11:34:37,336 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 11:34:37,339 - INFO - Total execution time: 1.65 seconds
2024-09-25 11:35:30,492 - INFO - Resolution: 10
2024-09-25 11:35:36,536 - INFO - > Available CUDA devices: 1
2024-09-25 11:35:36,537 - INFO - > Load the Minicube 0 ...
2024-09-25 11:35:36,542 - INFO - Resolution: 10
2024-09-25 11:35:41,005 - INFO - > Save the Minicube 0 ...
2024-09-25 11:35:41,273 - ERROR - An error occurred for index 0: b'\x80\x05\x95`\x07\x00\x00\x00\x00\x00\x00\x8c\x16tblib.pickling_support\x94\x8c\x12unpickle_exception\x94\x93\x94(\x8c\x08builtins\x94\x8c\x0cRuntimeError\x94\x93\x94\x8c\xfaError during deserialization of the task graph. This frequently\noccurs if the Scheduler and Client have different environments.\nFor more information, see\nhttps://docs.dask.org/en/stable/deployment-considerations.html#consistent-software-environments\n\x94\x85\x94h\x02(h\x03\x8c\x13ModuleNotFoundError\x94\x93\x94\x8c\x19No module named \'cytoolz\'\x94\x85\x94Nh\x00\x8c\x12unpickle_traceback\x94\x93\x94\x8c\x05tblib\x94\x8c\x05Frame\x94\x93\x94)\x81\x94}\x94(\x8c\x08f_locals\x94}\x94\x8c\tf_globals\x94}\x94(\x8c\x08__name__\x94\x8c\x15distributed.scheduler\x94\x8c\x08__file__\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94u\x8c\x06f_code\x94h\x0e\x8c\x04Code\x94\x93\x94)\x81\x94}\x94(\x8c\x0bco_filename\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94\x8c\x07co_name\x94\x8c\x0cupdate_graph\x94\x8c\x0bco_argcount\x94K\x00\x8c\x11co_kwonlyargcount\x94K\x00\x8c\x0bco_varnames\x94)\x8c\nco_nlocals\x94K\x00\x8c\x0cco_stacksize\x94K\x00\x8c\x08co_flags\x94K@\x8c\x0eco_firstlineno\x94K\x00ub\x8c\x08f_lineno\x94M\x80\x12ubMJ\x12h\x0e\x8c\tTraceback\x94\x93\x94)\x81\x94}\x94(\x8c\x08tb_frame\x94h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1edistributed.protocol.serialize\x94h\x19\x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94h"\x8c\x0bdeserialize\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\xc1\x01ub\x8c\ttb_lineno\x94M\xc1\x01\x8c\x07tb_next\x94h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h5h\x19h6uh\x1bh\x1d)\x81\x94}\x94(h h9h"\x8c\x0cpickle_loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Koubh;Koh<h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1bdistributed.protocol.pickle\x94h\x19\x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94h"\x8c\x05loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Kcubh;K^ububub\x87\x94R\x94N\x89Nt\x94R\x94}\x94\x8c\x04name\x94\x8c\x07cytoolz\x94sbh\rh\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h\x18h\x19h\x1auh\x1bh\x1d)\x81\x94}\x94(h h!h"h#h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\x80\x12ubMS\x12N\x87\x94R\x94hU\x88Nt\x94R\x94.'
2024-09-25 11:35:41,274 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 11:35:41,277 - INFO - Total execution time: 4.74 seconds
2024-09-25 11:56:45,490 - INFO - Resolution: 10
2024-09-25 11:57:07,102 - INFO - > Available CUDA devices: 1
2024-09-25 11:57:07,103 - INFO - > Load the Minicube 0 ...
2024-09-25 11:57:07,112 - INFO - Resolution: 10
2024-09-25 11:57:18,627 - INFO - > Save the Minicube 0 ...
2024-09-25 11:57:18,938 - ERROR - An error occurred for index 0: b'\x80\x05\x95`\x07\x00\x00\x00\x00\x00\x00\x8c\x16tblib.pickling_support\x94\x8c\x12unpickle_exception\x94\x93\x94(\x8c\x08builtins\x94\x8c\x0cRuntimeError\x94\x93\x94\x8c\xfaError during deserialization of the task graph. This frequently\noccurs if the Scheduler and Client have different environments.\nFor more information, see\nhttps://docs.dask.org/en/stable/deployment-considerations.html#consistent-software-environments\n\x94\x85\x94h\x02(h\x03\x8c\x13ModuleNotFoundError\x94\x93\x94\x8c\x19No module named \'cytoolz\'\x94\x85\x94Nh\x00\x8c\x12unpickle_traceback\x94\x93\x94\x8c\x05tblib\x94\x8c\x05Frame\x94\x93\x94)\x81\x94}\x94(\x8c\x08f_locals\x94}\x94\x8c\tf_globals\x94}\x94(\x8c\x08__name__\x94\x8c\x15distributed.scheduler\x94\x8c\x08__file__\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94u\x8c\x06f_code\x94h\x0e\x8c\x04Code\x94\x93\x94)\x81\x94}\x94(\x8c\x0bco_filename\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94\x8c\x07co_name\x94\x8c\x0cupdate_graph\x94\x8c\x0bco_argcount\x94K\x00\x8c\x11co_kwonlyargcount\x94K\x00\x8c\x0bco_varnames\x94)\x8c\nco_nlocals\x94K\x00\x8c\x0cco_stacksize\x94K\x00\x8c\x08co_flags\x94K@\x8c\x0eco_firstlineno\x94K\x00ub\x8c\x08f_lineno\x94M\x80\x12ubMJ\x12h\x0e\x8c\tTraceback\x94\x93\x94)\x81\x94}\x94(\x8c\x08tb_frame\x94h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1edistributed.protocol.serialize\x94h\x19\x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94h"\x8c\x0bdeserialize\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\xc1\x01ub\x8c\ttb_lineno\x94M\xc1\x01\x8c\x07tb_next\x94h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h5h\x19h6uh\x1bh\x1d)\x81\x94}\x94(h h9h"\x8c\x0cpickle_loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Koubh;Koh<h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1bdistributed.protocol.pickle\x94h\x19\x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94h"\x8c\x05loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Kcubh;K^ububub\x87\x94R\x94N\x89Nt\x94R\x94}\x94\x8c\x04name\x94\x8c\x07cytoolz\x94sbh\rh\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h\x18h\x19h\x1auh\x1bh\x1d)\x81\x94}\x94(h h!h"h#h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\x80\x12ubMS\x12N\x87\x94R\x94hU\x88Nt\x94R\x94.'
2024-09-25 11:57:18,940 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 11:57:18,943 - INFO - Total execution time: 11.84 seconds
2024-09-25 12:00:35,771 - INFO - Resolution: 10
2024-09-25 12:00:39,592 - INFO - > Available CUDA devices: 1
2024-09-25 12:00:39,593 - INFO - > Load the Minicube 0 ...
2024-09-25 12:00:39,598 - INFO - Resolution: 10
2024-09-25 12:00:43,284 - INFO - > Save the Minicube 0 ...
2024-09-25 12:00:43,595 - ERROR - An error occurred for index 0: b'\x80\x05\x95`\x07\x00\x00\x00\x00\x00\x00\x8c\x16tblib.pickling_support\x94\x8c\x12unpickle_exception\x94\x93\x94(\x8c\x08builtins\x94\x8c\x0cRuntimeError\x94\x93\x94\x8c\xfaError during deserialization of the task graph. This frequently\noccurs if the Scheduler and Client have different environments.\nFor more information, see\nhttps://docs.dask.org/en/stable/deployment-considerations.html#consistent-software-environments\n\x94\x85\x94h\x02(h\x03\x8c\x13ModuleNotFoundError\x94\x93\x94\x8c\x19No module named \'cytoolz\'\x94\x85\x94Nh\x00\x8c\x12unpickle_traceback\x94\x93\x94\x8c\x05tblib\x94\x8c\x05Frame\x94\x93\x94)\x81\x94}\x94(\x8c\x08f_locals\x94}\x94\x8c\tf_globals\x94}\x94(\x8c\x08__name__\x94\x8c\x15distributed.scheduler\x94\x8c\x08__file__\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94u\x8c\x06f_code\x94h\x0e\x8c\x04Code\x94\x93\x94)\x81\x94}\x94(\x8c\x0bco_filename\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94\x8c\x07co_name\x94\x8c\x0cupdate_graph\x94\x8c\x0bco_argcount\x94K\x00\x8c\x11co_kwonlyargcount\x94K\x00\x8c\x0bco_varnames\x94)\x8c\nco_nlocals\x94K\x00\x8c\x0cco_stacksize\x94K\x00\x8c\x08co_flags\x94K@\x8c\x0eco_firstlineno\x94K\x00ub\x8c\x08f_lineno\x94M\x80\x12ubMJ\x12h\x0e\x8c\tTraceback\x94\x93\x94)\x81\x94}\x94(\x8c\x08tb_frame\x94h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1edistributed.protocol.serialize\x94h\x19\x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94h"\x8c\x0bdeserialize\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\xc1\x01ub\x8c\ttb_lineno\x94M\xc1\x01\x8c\x07tb_next\x94h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h5h\x19h6uh\x1bh\x1d)\x81\x94}\x94(h h9h"\x8c\x0cpickle_loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Koubh;Koh<h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1bdistributed.protocol.pickle\x94h\x19\x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94h"\x8c\x05loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Kcubh;K^ububub\x87\x94R\x94N\x89Nt\x94R\x94}\x94\x8c\x04name\x94\x8c\x07cytoolz\x94sbh\rh\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h\x18h\x19h\x1auh\x1bh\x1d)\x81\x94}\x94(h h!h"h#h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\x80\x12ubMS\x12N\x87\x94R\x94hU\x88Nt\x94R\x94.'
2024-09-25 12:00:43,596 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 12:00:43,599 - INFO - Total execution time: 4.01 seconds
2024-09-25 12:02:31,273 - INFO - Resolution: 10
2024-09-25 12:02:36,190 - INFO - > Available CUDA devices: 1
2024-09-25 12:02:36,191 - INFO - > Load the Minicube 0 ...
2024-09-25 12:02:36,196 - INFO - Resolution: 10
2024-09-25 12:02:40,778 - INFO - > Save the Minicube 0 ...
2024-09-25 12:02:40,807 - ERROR - An error occurred for index 0: path '' contains a group
2024-09-25 12:02:40,807 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 12:02:40,810 - INFO - Total execution time: 4.65 seconds
2024-09-25 12:19:07,035 - INFO - Resolution: 10
2024-09-25 12:19:09,238 - INFO - > Available CUDA devices: 1
2024-09-25 12:19:09,239 - INFO - > Load the Minicube 0 ...
2024-09-25 12:19:09,244 - INFO - Resolution: 10
2024-09-25 12:19:10,917 - INFO - > Save the Minicube 0 ...
2024-09-25 12:19:11,201 - ERROR - An error occurred for index 0: b'\x80\x05\x95`\x07\x00\x00\x00\x00\x00\x00\x8c\x16tblib.pickling_support\x94\x8c\x12unpickle_exception\x94\x93\x94(\x8c\x08builtins\x94\x8c\x0cRuntimeError\x94\x93\x94\x8c\xfaError during deserialization of the task graph. This frequently\noccurs if the Scheduler and Client have different environments.\nFor more information, see\nhttps://docs.dask.org/en/stable/deployment-considerations.html#consistent-software-environments\n\x94\x85\x94h\x02(h\x03\x8c\x13ModuleNotFoundError\x94\x93\x94\x8c\x19No module named \'cytoolz\'\x94\x85\x94Nh\x00\x8c\x12unpickle_traceback\x94\x93\x94\x8c\x05tblib\x94\x8c\x05Frame\x94\x93\x94)\x81\x94}\x94(\x8c\x08f_locals\x94}\x94\x8c\tf_globals\x94}\x94(\x8c\x08__name__\x94\x8c\x15distributed.scheduler\x94\x8c\x08__file__\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94u\x8c\x06f_code\x94h\x0e\x8c\x04Code\x94\x93\x94)\x81\x94}\x94(\x8c\x0bco_filename\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94\x8c\x07co_name\x94\x8c\x0cupdate_graph\x94\x8c\x0bco_argcount\x94K\x00\x8c\x11co_kwonlyargcount\x94K\x00\x8c\x0bco_varnames\x94)\x8c\nco_nlocals\x94K\x00\x8c\x0cco_stacksize\x94K\x00\x8c\x08co_flags\x94K@\x8c\x0eco_firstlineno\x94K\x00ub\x8c\x08f_lineno\x94M\x80\x12ubMJ\x12h\x0e\x8c\tTraceback\x94\x93\x94)\x81\x94}\x94(\x8c\x08tb_frame\x94h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1edistributed.protocol.serialize\x94h\x19\x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94h"\x8c\x0bdeserialize\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\xc1\x01ub\x8c\ttb_lineno\x94M\xc1\x01\x8c\x07tb_next\x94h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h5h\x19h6uh\x1bh\x1d)\x81\x94}\x94(h h9h"\x8c\x0cpickle_loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Koubh;Koh<h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1bdistributed.protocol.pickle\x94h\x19\x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94h"\x8c\x05loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Kcubh;K^ububub\x87\x94R\x94N\x89Nt\x94R\x94}\x94\x8c\x04name\x94\x8c\x07cytoolz\x94sbh\rh\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h\x18h\x19h\x1auh\x1bh\x1d)\x81\x94}\x94(h h!h"h#h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\x80\x12ubMS\x12N\x87\x94R\x94hU\x88Nt\x94R\x94.'
2024-09-25 12:19:11,202 - INFO - > Load the Minicube 1 ...
2024-09-25 12:19:11,207 - INFO - Resolution: 10
2024-09-25 12:19:14,485 - INFO - > Save the Minicube 1 ...
2024-09-25 12:19:14,766 - ERROR - An error occurred for index 1: b'\x80\x05\x95`\x07\x00\x00\x00\x00\x00\x00\x8c\x16tblib.pickling_support\x94\x8c\x12unpickle_exception\x94\x93\x94(\x8c\x08builtins\x94\x8c\x0cRuntimeError\x94\x93\x94\x8c\xfaError during deserialization of the task graph. This frequently\noccurs if the Scheduler and Client have different environments.\nFor more information, see\nhttps://docs.dask.org/en/stable/deployment-considerations.html#consistent-software-environments\n\x94\x85\x94h\x02(h\x03\x8c\x13ModuleNotFoundError\x94\x93\x94\x8c\x19No module named \'cytoolz\'\x94\x85\x94Nh\x00\x8c\x12unpickle_traceback\x94\x93\x94\x8c\x05tblib\x94\x8c\x05Frame\x94\x93\x94)\x81\x94}\x94(\x8c\x08f_locals\x94}\x94\x8c\tf_globals\x94}\x94(\x8c\x08__name__\x94\x8c\x15distributed.scheduler\x94\x8c\x08__file__\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94u\x8c\x06f_code\x94h\x0e\x8c\x04Code\x94\x93\x94)\x81\x94}\x94(\x8c\x0bco_filename\x94\x8c`/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/scheduler.py\x94\x8c\x07co_name\x94\x8c\x0cupdate_graph\x94\x8c\x0bco_argcount\x94K\x00\x8c\x11co_kwonlyargcount\x94K\x00\x8c\x0bco_varnames\x94)\x8c\nco_nlocals\x94K\x00\x8c\x0cco_stacksize\x94K\x00\x8c\x08co_flags\x94K@\x8c\x0eco_firstlineno\x94K\x00ub\x8c\x08f_lineno\x94M\x80\x12ubMJ\x12h\x0e\x8c\tTraceback\x94\x93\x94)\x81\x94}\x94(\x8c\x08tb_frame\x94h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1edistributed.protocol.serialize\x94h\x19\x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8ci/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/serialize.py\x94h"\x8c\x0bdeserialize\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\xc1\x01ub\x8c\ttb_lineno\x94M\xc1\x01\x8c\x07tb_next\x94h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h5h\x19h6uh\x1bh\x1d)\x81\x94}\x94(h h9h"\x8c\x0cpickle_loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Koubh;Koh<h-)\x81\x94}\x94(h0h\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17\x8c\x1bdistributed.protocol.pickle\x94h\x19\x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94uh\x1bh\x1d)\x81\x94}\x94(h \x8cf/net/home/cmosig/miniconda3/envs/env_conda/lib/python3.12/site-packages/distributed/protocol/pickle.py\x94h"\x8c\x05loads\x94h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+Kcubh;K^ububub\x87\x94R\x94N\x89Nt\x94R\x94}\x94\x8c\x04name\x94\x8c\x07cytoolz\x94sbh\rh\x10)\x81\x94}\x94(h\x13}\x94h\x15}\x94(h\x17h\x18h\x19h\x1auh\x1bh\x1d)\x81\x94}\x94(h h!h"h#h$K\x00h%K\x00h&)h\'K\x00h(K\x00h)K@h*K\x00ubh+M\x80\x12ubMS\x12N\x87\x94R\x94hU\x88Nt\x94R\x94.'
2024-09-25 12:19:14,767 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 12:19:14,770 - INFO - Total execution time: 5.53 seconds
2024-09-25 12:25:22,836 - ERROR - Error in load_sentle function for index 2: single positional indexer is out-of-bounds
2024-09-25 12:25:29,483 - INFO - Resolution: 10
2024-09-25 12:25:31,374 - INFO - > Available CUDA devices: 1
2024-09-25 12:25:31,375 - INFO - > Load the Minicube 0 ...
2024-09-25 12:25:31,380 - INFO - Resolution: 10
2024-09-25 12:25:33,102 - INFO - > Save the Minicube 0 ...
2024-09-25 12:25:33,104 - ERROR - An error occurred for index 0: path '' contains a group
2024-09-25 12:25:33,120 - INFO - > Load the Minicube 1 ...
2024-09-25 12:25:33,124 - INFO - Resolution: 10
2024-09-25 12:25:36,078 - INFO - > Save the Minicube 1 ...
2024-09-25 12:25:36,080 - ERROR - An error occurred for index 1: path '' contains a group
2024-09-25 12:25:36,083 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 12:25:36,086 - INFO - Total execution time: 4.71 seconds
2024-09-25 12:26:46,892 - INFO - > Available CUDA devices: 1
2024-09-25 12:26:46,893 - INFO - > Load the Minicube 0 ...
2024-09-25 12:26:46,894 - INFO - Resolution: 10
2024-09-25 12:26:48,659 - INFO - > Save the Minicube 0 ...
2024-09-25 12:26:48,660 - ERROR - An error occurred for index 0: path '' contains a group
2024-09-25 12:26:48,663 - INFO - > Load the Minicube 1 ...
2024-09-25 12:26:48,667 - INFO - Resolution: 10
2024-09-25 12:26:51,533 - INFO - > Save the Minicube 1 ...
2024-09-25 12:26:51,535 - ERROR - An error occurred for index 1: path '' contains a group
2024-09-25 12:26:51,537 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 12:26:51,540 - INFO - Total execution time: 4.65 seconds
2024-09-25 12:31:46,689 - INFO - > Available CUDA devices: 1
2024-09-25 12:31:46,690 - ERROR - An error occurred in the main execution: name 'idx' is not defined
2024-09-25 12:31:46,695 - INFO - Total execution time: 0.01 seconds
2024-09-25 12:32:40,173 - INFO - > Available CUDA devices: 1
2024-09-25 12:32:40,174 - INFO - > Load the Minicube 38683078 ...
2024-09-25 12:32:40,180 - ERROR - Error in load_sentle function for index 38683078: single positional indexer is out-of-bounds
2024-09-25 12:32:40,184 - ERROR - An error occurred for index 38683078: single positional indexer is out-of-bounds
2024-09-25 12:32:40,189 - INFO - > Load the Minicube 38343098 ...
2024-09-25 12:32:40,193 - ERROR - Error in load_sentle function for index 38343098: single positional indexer is out-of-bounds
2024-09-25 12:32:40,196 - ERROR - An error occurred for index 38343098: single positional indexer is out-of-bounds
2024-09-25 12:32:40,200 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 12:32:40,203 - INFO - Total execution time: 0.03 seconds
2024-09-25 12:33:18,302 - INFO - > Available CUDA devices: 1
2024-09-25 12:33:18,303 - INFO - > Load the Minicube 0 ...
2024-09-25 12:33:18,307 - INFO - Resolution: 10
2024-09-25 12:33:20,382 - INFO - > Save the Minicube 0 ...
2024-09-25 12:33:20,383 - ERROR - An error occurred for index 0: name 'point_id' is not defined
2024-09-25 12:33:20,386 - INFO - > Load the Minicube 1 ...
2024-09-25 12:33:20,390 - INFO - Resolution: 10
2024-09-25 12:33:23,466 - INFO - > Save the Minicube 1 ...
2024-09-25 12:33:23,466 - ERROR - An error occurred for index 1: name 'point_id' is not defined
2024-09-25 12:33:23,483 - INFO - > Load the Minicube 2 ...
2024-09-25 12:33:23,504 - ERROR - Error in load_sentle function for index 2: single positional indexer is out-of-bounds
2024-09-25 12:33:23,508 - ERROR - An error occurred for index 2: single positional indexer is out-of-bounds
2024-09-25 12:33:23,511 - INFO - Total execution time: 5.21 seconds
2024-09-25 12:36:19,131 - INFO - Resolution: 10
2024-09-25 12:36:20,992 - INFO - > Available CUDA devices: 1
2024-09-25 12:36:20,993 - INFO - > Load the Minicube 0 ...
2024-09-25 12:36:20,998 - INFO - Resolution: 10
2024-09-25 12:36:22,831 - INFO - > Save the Minicube 0 ...
2024-09-25 12:36:22,833 - ERROR - An error occurred for index 0: path '' contains a group
2024-09-25 12:36:22,835 - INFO - > Load the Minicube 1 ...
2024-09-25 12:36:22,839 - INFO - Resolution: 10
2024-09-25 12:36:26,189 - INFO - > Save the Minicube 1 ...
2024-09-25 12:36:26,190 - ERROR - An error occurred for index 1: path '' contains a group
2024-09-25 12:36:26,193 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 12:36:26,196 - INFO - Total execution time: 5.20 seconds
2024-09-25 12:36:34,746 - ERROR - Error in load_sentle function for index 2: single positional indexer is out-of-bounds
2024-09-25 12:37:50,712 - INFO - Resolution: 10
2024-09-25 12:37:53,013 - INFO - > Available CUDA devices: 1
2024-09-25 12:37:53,014 - INFO - > Load the Minicube 0 ...
2024-09-25 12:37:53,032 - INFO - Resolution: 10
2024-09-25 12:37:55,060 - INFO - > Save the Minicube 0 ...
2024-09-25 12:37:55,065 - ERROR - An error occurred for index 0: path '' contains a group
2024-09-25 12:37:55,065 - INFO - > Load the Minicube 1 ...
2024-09-25 12:37:55,069 - INFO - Resolution: 10
2024-09-25 12:37:58,515 - INFO - > Save the Minicube 1 ...
2024-09-25 12:37:58,517 - ERROR - An error occurred for index 1: path '' contains a group
2024-09-25 12:37:58,519 - ERROR - An error occurred in the main execution: single positional indexer is out-of-bounds
2024-09-25 12:37:58,525 - INFO - Total execution time: 5.51 seconds
2024-09-25 12:45:22,537 - INFO - Resolution: 10
2024-09-25 12:45:24,215 - INFO - > Available CUDA devices: 1
2024-09-25 12:45:24,218 - ERROR - An error occurred in the main execution: process_and_save() missing 2 required positional arguments: 'point_id' and 'res'
2024-09-25 12:45:24,222 - INFO - Total execution time: 0.01 seconds
2024-09-25 13:01:02,975 - ERROR - Error in load_sentle function for index 1: int() argument must be a string, a bytes-like object or a real number, not 'list'
2024-09-25 13:01:18,247 - INFO - Resolution: 10
2024-09-25 13:01:21,925 - ERROR - Error in load_sentle function for index 1: name 'lcs_cpns_poly' is not defined
2024-09-25 13:01:46,248 - INFO - Resolution: 10
2024-09-25 13:02:14,523 - INFO - Resolution: 10
2024-09-25 13:09:52,913 - INFO - Resolution: 10
2024-09-25 13:10:59,584 - ERROR - Error in load_sentle function for index 2: single positional indexer is out-of-bounds
2024-09-25 13:11:02,469 - INFO - Resolution: 10
2024-09-25 13:19:56,633 - INFO - Resolution: 10
2024-09-25 13:28:16,603 - INFO - Resolution: 10
2024-09-25 13:31:55,765 - INFO - Resolution: 10
2024-09-25 13:34:35,450 - INFO - Resolution: 10
2024-09-25 13:35:16,440 - INFO - Resolution: 10
2024-09-25 13:37:23,620 - INFO - Resolution: 10
2024-09-25 15:29:24,105 - INFO - Resolution: 10
2024-09-25 15:29:24,936 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-25 15:35:09,725 - INFO - Resolution: 10
2024-09-25 15:35:10,634 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-25 15:35:45,723 - INFO - Resolution: 10
2024-09-25 15:35:46,542 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-25 15:40:14,906 - INFO - Resolution: 10
2024-09-25 15:40:15,767 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-25 15:43:27,438 - INFO - Resolution: 10
2024-09-25 15:43:28,482 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 15:45:46,969 - INFO - Resolution: 10
2024-09-25 15:45:47,949 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 15:46:33,028 - INFO - Resolution: 10
2024-09-25 15:46:34,077 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 15:47:10,949 - INFO - Resolution: 10
2024-09-25 15:47:12,152 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 15:59:45,055 - INFO - Resolution: 10
2024-09-25 15:59:46,059 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 16:02:48,947 - INFO - Resolution: 10
2024-09-25 16:02:49,945 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 16:06:33,064 - INFO - Resolution: 10
2024-09-25 16:06:34,092 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 16:09:03,331 - INFO - Resolution: 10
2024-09-25 16:09:04,335 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 16:11:59,702 - INFO - Resolution: 10
2024-09-25 16:12:00,685 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 16:12:34,617 - INFO - Resolution: 10
2024-09-25 16:12:35,603 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 16:13:21,258 - INFO - Resolution: 10
2024-09-25 16:13:22,181 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 16:14:21,501 - INFO - Resolution: 10
2024-09-25 16:14:22,452 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 16:16:22,881 - INFO - Resolution: 10
2024-09-25 16:16:23,971 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-25 16:17:32,300 - INFO - Resolution: 10
2024-09-25 16:17:33,320 - ERROR - Error in load_sentle function for index 0: The WKT could not be parsed. OGR Error code 6
2024-09-26 11:25:08,884 - INFO - Resolution: 10
2024-09-26 11:25:09,756 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-26 11:59:08,462 - INFO - Resolution: 10
2024-09-26 11:59:09,656 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
2024-09-26 12:06:32,245 - INFO - Resolution: 10
2024-09-26 12:06:33,061 - ERROR - Error in load_sentle function for index 0: VariableExtension.set() got an unexpected keyword argument 'timeout'
